### ISSUE TITLE
Menu Desktop to Mobile

### ISSUE THREAD

**Issue by mdestafadilah** [jbtalhakhan/react-tailwind-food-app#1]
I'm testing live version with Win10 and Chrome, the Menu is not auto detect.

**Comment by jbdotjs** [comment]
Thank you for testing. I've implemented javascript based check for smaller
screen size (which I'll change for a media query) so you'll need to reload
the page for desktop/mobile version. Moreover, the hamburger menu is also
in the making and I haven't pushed that live yet.

**Comment by mdestafadilah** [comment]
Yes, I must reload then menu changed, but it's not like, bootstrap. or media query, may you update it ASAP. 

Thanks for your hard work.

**Comment by jbdotjs** [comment]
Will do, thanks!

**Comment by jbdotjs** [comment]
I've added the responsive hamburger menu, kindly do check.

**Comment by mdestafadilah** [comment]
Thanks for quick response, i'll check too. Amazing work!
